language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"


env:
  global:
  matrix:
    - WITH_OPENTREP=0
    - WITH_OPENTREP=1


matrix:
  allow_failures:
    - python: "2.5"


notifications:
  email:
      - alexprengere@gmail.com

# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script: "python test/test_GeoBases.py -vv"
