language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"


env:
  global:
  matrix:
    - WITH_OPENTREP=0
    - WITH_OPENTREP=1


matrix:
  allow_failures:
    - python: "3.0"
    - python: "3.1"
    - python: "3.3"


notifications:
  email:
      - alexprengere@gmail.com


# command to install dependencies
install:
    - "python setup.py install"

# command to run tests
script: "python test/test_GeoBases.py -vv"
